### ISSUE TITLE
Consider creating a "compiled" container

### ISSUE THREAD

**Issue by meadsteve** [meadsteve/lagom#5]
Since the container implements a dictionary interface it should be possible to analyse the code and generate a dictionary that can be dropped in place of the container.  This would avoid any reflection happening at runtime.

**Comment by meadsteve** [comment]
TODO: some profiling to determine if this is worth it from a performance point of view.

**Comment by meadsteve** [comment]
Lazy profiling.

This script takes roughly 25 seconds to run:
```python
from lagom import Container, Singleton, bind_to_container, Alias
import time


class SomeService:
    def do_it(self):
        pass


class AThingIMightNeed:
    service: SomeService

    def __init__(self, service: SomeService):
        self.service = service

    def do_it(self):
        self.service.do_it()


container = Container()


@bind_to_container(container)
def do_work(thing: AThingIMightNeed):
    thing.do_it()


if __name__ == "__main__":
    start = time.perf_counter()
    for i in range(0, 100_000):
        do_work()
    end = time.perf_counter()
    print(f"Time taken {end - start}")
```

add the dependency definitions drops it down to 3.5 seconds:
```python
container[AThingIMightNeed] = lambda c: AThingIMightNeed(c[SomeService])
container[SomeService] = lambda: SomeService()
```

**Comment by meadsteve** [comment]
The above comment is now less relevant as caching the reflection results and refactoring have brought the speed down a lot. The compiled container approach however still addresses the "what the magic is going on" question.

**Comment by RobertoPrevato** [comment]
Hi @meadsteve,
I just came across your project, it looks interesting. I'm fascinated by how type annotations are enabling non-invasive implementations of dependency injection for Python.

I am also the author of a library for dependency injection, [rodi](https://github.com/Neoteroi/rodi).

I am commenting under this issue because in my case, I saw that running inspections only once does pay off in terms of performance. A few days ago [I tweeted about this subject](https://twitter.com/RobertoPrevato/status/1355867182387900417), and published a piece of code to compare my implementation, that does include this optimization, with **punq**, a similar implementation that does not include that optimization.

**Comment by RobertoPrevato** [comment]
@meadsteve 

I just prepared a test, in a few minutes, and your implementation is even faster than mine, when using lambdas 🎉 
like in this example:

```python
import os

import lagom

container = lagom.Container()


class ConfigReader:
    def get_config(self):
        pass


class EnvironmentConfigReader(ConfigReader):
    def get_config(self):
        return {
            "logging": {"level": os.environ.get("LOGGING_LEVEL", "debug")},
            "greeting": os.environ.get("GREETING", "Hello world"),
        }


class Greeter:
    def greet(self):
        pass


class ConsoleGreeter:
    def __init__(self, config_reader: ConfigReader):
        self.config = config_reader.get_config()

    def greet(self):
        print(self.config["greeting"])


container[ConfigReader] = lambda: EnvironmentConfigReader()
container[Greeter] = lambda c: ConsoleGreeter(c[ConfigReader])


def lagom_main():
    greeter = container.resolve(Greeter)
    assert isinstance(greeter, ConsoleGreeter)


if __name__ == "__main__":
    lagom_main()

```

![image](https://user-images.githubusercontent.com/2576032/111900728-8341eb80-8a34-11eb-9460-8d8567f0c6b3.png)

And when I don't use a lambda for `Greeter` class it's only a bit slower (the difference is minimal in both cases):

```python
import os

import lagom

container = lagom.Container()


class ConfigReader:
    def get_config(self):
        pass


class EnvironmentConfigReader(ConfigReader):
    def get_config(self):
        return {
            "logging": {"level": os.environ.get("LOGGING_LEVEL", "debug")},
            "greeting": os.environ.get("GREETING", "Hello world"),
        }


class Greeter:
    def greet(self):
        pass


class ConsoleGreeter:
    def __init__(self, config_reader: ConfigReader):
        self.config = config_reader.get_config()

    def greet(self):
        print(self.config["greeting"])


container[ConfigReader] = lambda: EnvironmentConfigReader()


def lagom_main():
    greeter = container.resolve(ConsoleGreeter)
    assert isinstance(greeter, ConsoleGreeter)


if __name__ == "__main__":
    lagom_main()

```

![image](https://user-images.githubusercontent.com/2576032/111900845-0cf1b900-8a35-11eb-9848-9c7bd309af7f.png)

I added the code to my repository with the comparison (link in my tweet).

**Comment by meadsteve** [comment]
@RobertoPrevato thanks for the input. I'll take a look at yours as it sounds like we've taken very similar approaches. 

I implemented cached reflection to give a little speed boost a while back. My intention was largely that the reflected version is an early stage development tool with users moving to explicit lambdas once they stabilise:

https://lagom-di.readthedocs.io/en/latest/explicit_definitions/

For ABC type use cases I implemented aliases if you don't want to use a lambda so:

`container[Greeter] = ConsoleGreater` will configure the container to load the console type whenever an ABC is asked for.

**Comment by RobertoPrevato** [comment]
It looks great! I did my implementation taking inspiration from of the [.NET Core one](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.1), which I know for my work in C# for ASP.NET Core applications. Like in the .NET one, I first require to register services explicitly in a container, then to create a "service provider" by calling "container.build_provider()".

All inspections are run only once, and I generate factories in memory to activate services. The code is a bit mind-bending, especially because I support the same life-times of the .NET implementation (singleton, scoped, transient) - the scoped one increases complexity.

I wanted to have the same for my Python web framework, and I am so satisfied with the way web applications come together when using dependency injection. I wrote a bit about this here: [https://www.neoteroi.dev/blacksheep/dependency-injection/](https://www.neoteroi.dev/blacksheep/dependency-injection/).

Maybe I will refactor BlackSheep to add support for your `lagom`. 🙂

**Comment by meadsteve** [comment]
The explicit container covers everything I'd want with a compiled container and I actually prefer this approach as it's then owned by the codebase and doesn't require any extra compiling steps so is simpler.

Closing this issue as it's now not something I plan for lagom at least medium term.

reference: https://lagom-di.readthedocs.io/en/stable/explicit_definitions/
